### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by janderson099** [ctf0/vscode-save-editor-layout#1]
Hi.
When I try to save regular tabs, not temporaries, this error appears:
![image](https://user-images.githubusercontent.com/35040917/88919765-175f0880-d242-11ea-8662-00ead8f7bf8d.png)

It was also reported here:
https://stackoverflow.com/questions/62364114/saving-editor-layout

**Comment by ctf0** [comment]
yes this is expected, because when closing the opened tabs, untitled wont be restored

**Comment by janderson099** [comment]
> yes this is expected, because when closing the opened tabs, untitled wont be restored

Yeah, but the opened tabs are saved.
Here's a printscreen:
![image](https://user-images.githubusercontent.com/35040917/88965269-e4883500-d280-11ea-9826-64add0c6e808.png)

Thank you for your attention.

**Comment by ctf0** [comment]
yes i can see, I will retest and reply back

**Comment by ctf0** [comment]
can u tell me the path structures of the files ?

what happens is we check if the file filename includes a `/` which means its saved somewhere on the HDD, otherwise its being treated as `untitled file`

also if you can give me an exact steps to follow it would be very helpful 🏆

**Comment by janderson099** [comment]
> can u tell me the path structures of the files ?

For the screenshot above the path is: `D:\_Clients\MLC-2\DEP-Phase1\fe-library\productstore\source\_patterns\`

> 
> what happens is we check if the file filename includes a `/` which means its saved somewhere on the HDD, otherwise its being treated as `untitled file`

Ok. The path has a `/`

> 
> also if you can give me an exact steps to follow it would be very helpful 🏆

### Steps
- Go to Extensions
- Search and install the "Save Editors Layout" (v.0.0.9)
- Open a project
- Open some files
- Click on the icon of the "Save Editors Layout"
![image](https://user-images.githubusercontent.com/35040917/89024898-3fab3d80-d2fc-11ea-8143-806c413fbea6.png)

- Click on the icon "save group": 
![image](https://user-images.githubusercontent.com/35040917/89024480-8e0c0c80-d2fb-11ea-9f43-29ece4efd850.png)

- Throws an error: "FSC: "5 Untitled" tabs cant be saved because they are temporary"

Below, a screenshot of the console, inside VSCode:
![image](https://user-images.githubusercontent.com/35040917/89023884-a596c580-d2fa-11ea-809e-ab83e93ca28f.png)

**Comment by ctf0** [comment]
thanx for replying back, i've just retested and all working as expected.

here is my env info
```
Version: 1.48.0-insider
Commit: c9a2f78283b6e5ef708fb8869e2a5adaa476e42f
Date: 2020-07-31T07:35:12.881Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

i haven't tested the ext on windows though, but could u try to manually update the ext with 
https://github.com/ctf0/vscode-save-editor-layout/blob/98e7131484c644e07f4d565ee163bb9cc5f83cd3/src/extension.js#L259

and see if it fix ur issue ?

**Comment by janderson099** [comment]
> thanx for replying back, i've just retested and all working as expected.
> 
> here is my env info
> 
> ```
> Version: 1.48.0-insider
> Commit: c9a2f78283b6e5ef708fb8869e2a5adaa476e42f
> Date: 2020-07-31T07:35:12.881Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 18.7.0
> ```
> 
> i haven't tested the ext on windows though, but could u try to manually upload the ext with
> https://github.com/ctf0/vscode-save-editor-layout/blob/98e7131484c644e07f4d565ee163bb9cc5f83cd3/src/extension.js#L259
> 
> and see if it fix ur issue ?

Yes, it's fixed!
I changed line 259 and restarted VSCode.
Thank you very much.

**Comment by ctf0** [comment]
i will release a new version with the new changes today, thanx for reporting.
