### ISSUE TITLE
Enhancement: Support secondary sidebar

### ISSUE THREAD

**Issue by chipbite** [ctf0/vscode-save-editor-layout#12]
Nitpick: Support for secondary sidebar could be more clear. 
I did manage to move the view into the secondary sidebar, by doing a bit of switching around, but it was not clear.

( I move timeline to secondary sidebar, and then switched to view save editor groups panel in primary, then moved timeline to above save editor groups in primary sidebar, and then I could grab and move save editor groups view to secondary sidebar)

**Comment by ctf0** [comment]
related https://github.com/ctf0/vscode-save-editor-layout/issues/10
