### ISSUE TITLE
Possible regression: absolute paths used in saving

### ISSUE THREAD

**Issue by firdimigdi** [ctf0/vscode-save-editor-layout#13]
Hi there and thanks for this handy addon,

According to the changelog at some point there was the option to save relative paths instead of absolute but it seems that newer versions don't do this and the configuration setting mentioned (saveEditorLayout.saveAbsolutePath) doesn't seem to exist any more. Is there any chance this might have a come-back at some point?

**Comment by ctf0** [comment]
i honstly cant remember why i added/remove it, however if you still need it am open to PRs.
