### ISSUE TITLE
Hope to add support for relative paths

### ISSUE THREAD

**Issue by cliuyang** [ctf0/vscode-save-editor-layout#2]
You may not imagine how EXCITED I am after seeing this project! I have been looking for a way to save the vscode layout. 

I have been exploring the best practices for using vscode for algorithm competitions. You can see what I have done through this screenshot.

![image](https://user-images.githubusercontent.com/39078310/104103981-2dd4ba00-52e0-11eb-8dc8-eb39f3649717.png)

![2021-01-10_00-56](https://user-images.githubusercontent.com/39078310/104103842-4db7ae00-52df-11eb-9083-509a18f6b3d2.png)

My idea is to save this folder as a template and make a copy for use during the competition. But every time I open the folder with vscode, I have to re-layout. So vscode-save-editor-layout is exactly the extension I am looking for.

But now vscode-save-editor-layout only supports absolute paths. If I want to realize my idea, I must use relative paths. In fact, vscode-save-editor-layout works in a workspace where relative paths are more suitable than absolute paths. Therefore, can support for relative paths be increased?

In addition, can I specify a saved layout as the default layout and use it directly when opening the folder? This is very meaningful for a specific type of workspace.

I noticed that because of the lack of API, vscode-save-editor-layout can only support horizontal layout but not vertical layout, which is really a pity. :(  But step by step, I think the function of saving the layout will be very useful. Thank you for your efforts.

I used Google Translate to translate from Chinese to English, so there may be some grammatical errors. Thanks again.

**Comment by ctf0** [comment]
hi @cliuyang glad u liked the ext.

> Therefore, can support for relative paths be increased?

can u tell how the path looks like & how to recreate one to test with ?

> can I specify a saved layout as the default layout and use it directly when opening the folder?

this wont work as expected because it means that the ext will need to have some way of deciding what file will be saved in which group/column.

> I used Google Translate to translate from Chinese to English, so there may be some grammatical errors. Thanks again.

no worries 👍

**Comment by cliuyang** [comment]
hi @ctf0 this is what i mean

> can u tell how the path looks like

Below is the path currently generated by vscode-save-editor-layout

![settings](https://user-images.githubusercontent.com/39078310/104200985-3a821b00-5464-11eb-8c09-1521d8d65a8c.png)

This path looks like`/media/frankchen/Document/UbuntuOneDrive/storage-space/codeforces/C++ Algorithm Competition Template/src/A.cpp`

My expected path is`./src/A.cpp`

> how to recreate one to test with ?

Use the following steps to create a folder that is only used for testing. I will use pictures and shell codes to describe some ambiguous steps

1. Create a new template folder and use vscode to open the template file, for example, use the following command

   ```shell
   mkdir template_folder
   code template_folder/
   ```
    ![template_folder_empty](https://user-images.githubusercontent.com/39078310/104201992-50dca680-5465-11eb-829b-c7da54e78e80.png)

2. Create several cpp source files and input and output files
   ![template_folder_create_files](https://user-images.githubusercontent.com/39078310/104201142-61d8e800-5464-11eb-82f3-b707e08c584b.png)
3. Drag the editor to set the desired layout
   ![template_folder_layout](https://user-images.githubusercontent.com/39078310/104201230-7d43f300-5464-11eb-9e3f-d840a2ccd5cb.png)
4. Use vscode-save-editor-layout to save the layout and name it`algorithm`
    ![template_folder_save_group](https://user-images.githubusercontent.com/39078310/104201292-8cc33c00-5464-11eb-91cf-a65fadecf481.png)
    ![template_folder_rename_group](https://user-images.githubusercontent.com/39078310/104201323-964ca400-5464-11eb-9c08-dc59eea4fb33.png)
    ![template_folder_save_group_sucess](https://user-images.githubusercontent.com/39078310/104201354-9fd60c00-5464-11eb-86a5-426cb8efddc8.png)
5. Close vscode
6. Copy the template folder and rename it, or use the following command

   ```shell
   cp -r test_folder Codeforces_Round
   ```

7. Use vscode to open a new folder, or use the following command

   ```shell
   vscode Codeforces_Round
   ```

8. Use vscode-save-editor-layout to open the previously set group
   ![codeforces_folder_open_group](https://user-images.githubusercontent.com/39078310/104201402-aebcbe80-5464-11eb-9ad9-3298aae6d538.png)
   ![codeforces_folder_choose_group](https://user-images.githubusercontent.com/39078310/104201945-40c4c700-5465-11eb-89b2-d6265619d5ef.png)


9. What I expect is that the layout of vscode will become like this after opening the group
    ![codeforces_folder_open_group_sucess](https://user-images.githubusercontent.com/39078310/104201442-bbd9ad80-5464-11eb-86d5-2ce5d4680816.png)
   But the current result of vscode-save-editor-layout is
    ![codeforces_folder_open_group_fail](https://user-images.githubusercontent.com/39078310/104201493-c98f3300-5464-11eb-86fe-a46aeb07a8fc.png)


> this wont work as expected because it means that the ext will need to have some way of deciding what file will be saved in which group/column.

I think what I am looking forward to is that the steps 7 and 8 above are **automatically** carried out. In other words, I set a saved group as the default group, and then automatically use the group when opening this folder. Reflected in `settings.json`, it looks like this setting:

![default](https://user-images.githubusercontent.com/39078310/104201536-d744b880-5464-11eb-901f-7560b44df385.png)

**Comment by ctf0** [comment]
> My expected path is./src/A.cpp

the reason we use full path is so u can open the file no matter the active workspace is, with relative path, it means we will have to resolve according to current workspace path.

> 8.Use vscode-save-editor-layout to open the previously set group

after u save the layout, open the ext view and hover on each file, u will find 4 navigation icons, which we use as a way around to force aligning the file to the rows/columns we want "this doesnt support nested groups though" check https://github.com/ctf0/vscode-save-editor-layout/blob/master/CHANGELOG.md#005

> I set a saved group as the default group, and then automatically use the group when opening this folder

if i understand u correctly,  u want to open folders in a default layout, if yes then i think it could be done in one of this options
- have an option to toggle a saved group to either open its files in the layout or create an empty layout so u can add files later
  - to lay a folder files automatically on the opened group, this will need more work & it wont be as easy as we dont have an API to know where files are aligned.
- have an option to save current layout without files "empty layout"

**Comment by ctf0** [comment]
**update**

currently using the arrows doesnt produce the intended, not sure if something has changed in vscode or its a bug of mine, anyway will work on it later when i have time, hang in there.

**Comment by ctf0** [comment]
for `relative path` i have an idea for it,
for `default layout` its under a new ticket https://github.com/ctf0/vscode-save-editor-layout/issues/3

**Comment by ctf0** [comment]
@cliuyang can u check the latest release and tell me if it helps with ur issue ?

**Comment by cliuyang** [comment]
@ctf0 
It works better in saving and opening layouts, which makes me very happy. Thanks a lot. :)

But I did not understand the meaning of the `Save To Global` setting. It seems that it supports saving the layout in the workspace? But it still uses the full path, the difference is that the saved location is different.

I usually open a folder with vscode, this folder is my workspace. When I copy, move, and rename this folder, I hope that the saved layout can still be used.

As I said before, I often use vscode for algorithm competitions. My habit is to set up a template folder, copy it during the competition, and use it after renaming. I hope the *Save Editor Layout* can also be used in such occasions.

**Comment by ctf0** [comment]
yeah yeah, the relative path option is not added yet, i was just testing if the latest changes made ur usage easier than b4 or not.

**Comment by cliuyang** [comment]
Then I have to boast, the new version supports more complex layout settings, and the experience is very good.☺️

**Comment by ctf0** [comment]
check latest release, relative path is now live.

**Comment by cliuyang** [comment]
Really cool job! Thanks a lot! lol
