### ISSUE TITLE
VS code sidebar closes when opening group

### ISSUE THREAD

**Issue by user72356** [ctf0/vscode-save-editor-layout#6]
It's a small nitpick but it gets annoying with repeated usage. The VS Code primary sidebar closes any time I open a saved group. Is there any way to keep it the same state that it was when the group is opened?

**Comment by ctf0** [comment]
will recheck it

**Comment by ctf0** [comment]
we currenctly have `saveEditorLayout.hideSideBarAfterOpen` is that what u r after ?

**Comment by user72356** [comment]
You're totally right, completely missed that setting! Thank you!
