### ISSUE TITLE
Feature Request: Ability to store/save layout without touching open files

### ISSUE THREAD

**Issue by Gaibhne** [ctf0/vscode-save-editor-layout#9]
VSCode has the chronic issue of resizing and moving windows, tabs and views when resolution changes (which often happens for people remoting into their work PC), and this extension is great for restoring the layout after it gets mangled. But I pretty much never want it to open specific files (though I would have a use case for 'open saved files, but leave layout alone'). Maybe when saving one could specify what should be saved ?

**Comment by ctf0** [comment]
u mean saving/restoring the layout only?

**Comment by Gaibhne** [comment]
Yes (and as a second option saving/restoring layout only).

My use cases:

I use VSCode on the physical PC, as well as via remote. When I remote in, the resolution changes, and my layout gets messed up, and since I have three screens at work, two at home, my work layout and home layout are different.

Use case 1: I have my files open how I like them, but then I switch from remote to non-remote or back, and my layout is messed up. In case 1, I want to load only my saved remote/non-remote layout, while leaving the files however they currently are.

Use case 2: I have a set of files I want to save with this extension, but I want to be able to load the saved list whether I am remote or non-remote. Currently, it saves both layout+files, so when I have to save two file lists, one with the remote layout and one with then on-remote layout. In case 2, I want to load only my saved file list, while leaving the layout alone.

Could be done either letting you chose files+layout, just files or just layout when you save, or when you load (or both), but my usual work flow is I save things half a dozen times, but load them many many times, so I would prefer the loading not ask me questions.

Does that make sense ?

**Comment by ctf0** [comment]
i can for now create a config that allow restoring layout only without opening the files, for other options i would add them via PRs.

**Comment by ctf0** [comment]
check latest release for the layout option.

**Comment by Gaibhne** [comment]
That works well for me, thanks!
